language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t zelucena/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true zelucena/react-test npm test

after_success:
  - docker build -t zelucena/multi-client ./client
  - docker build -t zelucena/multi-nginx ./nginx
  - docker build -t zelucena/multi-server ./server
  - docker build -t zelucena/multi-worker ./worker

  # log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "${DOCKER_ID}" -- password-stdin

  # take those images and push them to docker hub
  - docker push zelucena/multi-client
  - docker push zelucena/multi-nginx 
  - docker push zelucena/multi-server
  - docker push zelucena/multi-worker